export const EVENTS = {
  CANVAS: {
    CREATED: 'CANVAS_CREATED',
    RESET: 'CANVAS_RESET',
  },
  TOOL: {
    SELECTED: 'TOOL_SELECTED',
  },
  LAYER: {
    DROPPED: 'LAYER_DROPPED',
    REORDERED: 'LAYERS_REORDERED',
    UPDATED: 'LAYERS_UPDATED',
  },
  PROPERTY: {
    COLOR_CHANGED: 'COLOR_CHANGED',
    WIDTH_CHANGED: 'WIDTH_CHANGED',
    HEIGHT_CHANGED: 'HEIGHT_CHANGED',
    OPACITY_CHANGED: 'OPACITY_CHANGED',
    TEXT_CHANGED: 'TEXT_CHANGED',
  },
};
